name: MAPE-PPI
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # PyTorch dependencies, you may change to your preferred version.
  - pytorch==2.0.0
  - cudatoolkit=11.7
  - dglteam::dgl-cuda11.7
  - pip=22.2.2=pyhd8ed1ab_0
  # Others
  - pip:
      - numpy==1.20.1
      - csv==1.0
      - json==2.0.9
      - nni==2.10
      - argparse==1.1
